In [1]:
import pandas as pd
import requests
import os

In [2]:
# --- Load the CSV file saved from original notebook ---
catalog_summary = pd.read_csv('/home/emmay/BL2025/catalog_summary.csv')  # Adjust path if needed
catalog_summary

/tmp/ipykernel_1834797/3918354451.py:2: DtypeWarning: Columns (15,21) have mixed types. Specify dtype option on import or set low_memory=False.
  catalog_summary = pd.read_csv('/home/emmay/BL2025/catalog_summary.csv')  # Adjust path if needed

,GCNS_name,GCNS_RA,GCNS_DEC,Dist50,Gmag,gmag,BPmag,RPmag,is_in_GaiaESO,GaiaESO_name,...,HARPS_name,is_in_APOGEE,APOGEE_name,is_in_CARMENES,CARMENES_name,any_match,BP_RP,num_catalog_matches,is_in_GALAH,GALAH_name
0,2334666126716440064,0.002565,-26.365350,0.06803,15.7779,17.796,17.4299,14.5407,0,NaN,...,NaN,0,NaN,0,NaN,0,2.8892,0,0,NaN
1,2341871673090078592,0.005121,-19.498841,0.03739,8.9429,9.979,9.4761,8.2513,0,NaN,...,NaN,0,NaN,0,NaN,0,1.2248,0,0,NaN
2,530861741656374272,0.005637,70.887364,0.09726,10.8521,NaN,11.3022,10.2396,0,NaN,...,NaN,0,NaN,0,NaN,0,1.0626,0,0,NaN
3,2745400068346761216,0.009336,6.511017,0.06152,16.2772,18.661,18.2886,14.9456,0,NaN,...,NaN,0,NaN,0,NaN,0,3.3430,0,0,NaN
4,2855176271335676800,0.013536,29.277896,0.09716,15.6236,17.406,17.0649,14.4501,0,NaN,...,NaN,0,NaN,0,NaN,0,2.6148,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331307,2766925825958528512,359.993523,12.376062,0.04419,15.7297,18.028,17.6646,14.4268,0,NaN,...,NaN,0,NaN,0,NaN,0,3.2378,0,0,NaN
331308,2773791481503524992,359.994028,18.053030,0.06992,18.8258,22.137,21.0958,17.2938,0,NaN,...,NaN,0,NaN,0,NaN,0,3.8020,0,0,NaN
331309,6521388186590534272,359.994771,-53.182288,0.05524,14.8102,16.638,16.4323,13.5842,0,NaN,...,NaN,0,NaN,0,NaN,0,2.8481,0,0,NaN
331310,2011682661920690304,359.995813,60.918306,0.11096,17.4743,19.190,18.7381,15.6945,0,NaN,...,NaN,0,NaN,0,NaN,0,3.0436,0,0,NaN
331311,2314850075324449408,359.999926,-30.024529,0.08836,19.2646,NaN,21.1853,17.8008,0,NaN,...,NaN,0,NaN,0,NaN,0,3.3845,0,0,NaN

In [7]:
catalog_summary[catalog_summary['is_in_GALAH'] == 1]

,GCNS_name,GCNS_RA,GCNS_DEC,Dist50,Gmag,gmag,BPmag,RPmag,is_in_GaiaESO,GaiaESO_name,...,HARPS_name,is_in_APOGEE,APOGEE_name,is_in_CARMENES,CARMENES_name,any_match,BP_RP,num_catalog_matches,is_in_GALAH,GALAH_name
11,4922504834475892480,0.021016,-56.994235,0.06431,13.3305,14.584,14.4752,12.2609,0,NaN,...,NaN,0,NaN,0,NaN,0,2.2143,0,1,1.611160e+14
14,2740314311671472256,0.024477,3.891875,0.07129,14.3447,16.153,15.7994,13.1627,0,NaN,...,NaN,0,NaN,0,NaN,0,2.6367,0,1,1.709100e+14
191,4976484155252771584,0.206140,-50.981097,0.06263,14.2942,15.963,15.8562,13.0821,0,NaN,...,NaN,0,NaN,0,NaN,0,2.7741,0,1,1.611180e+14
198,4973387586910877440,0.213421,-51.786837,0.09612,13.7426,14.987,14.8502,12.6946,0,NaN,...,NaN,0,NaN,0,NaN,0,2.1556,0,1,1.611180e+14
220,4899939316820772992,0.243177,-66.058417,0.09359,12.2531,13.100,13.0258,11.3962,0,NaN,...,NaN,0,NaN,0,NaN,0,1.6296,0,1,2.010020e+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330733,6521277994908662272,359.366706,-53.331335,0.07087,13.8320,15.420,15.2532,12.6594,0,NaN,...,NaN,0,NaN,0,NaN,0,2.5938,0,1,2.008010e+14
330877,2745285444258763904,359.513341,6.034146,0.05217,12.5491,14.102,13.7089,11.4739,0,NaN,...,NaN,0,NaN,0,NaN,0,2.2350,0,1,1.611170e+14
330898,6521265762841775872,359.534314,-53.678185,0.09264,13.7855,15.173,15.0219,12.6816,0,NaN,...,NaN,0,NaN,0,NaN,0,2.3403,0,1,2.008010e+14
331020,6389064092489933056,359.647964,-66.931327,0.09642,13.7497,14.934,14.8413,12.7088,0,NaN,...,NaN,0,NaN,0,NaN,0,2.1325,0,1,2.010020e+14
331034,6386116611053690112,359.668009,-72.004991,0.05709,14.0096,15.407,15.2833,12.8962,0,NaN,...,NaN,0,NaN,0,NaN,0,2.3871,0,1,1.508270e+14

In [8]:
def download_galah_fits(catalog_summary, output_dir="/datax/scratch/emmay/galah_spectra"):
    """
    Download GALAH FITS files for up to 100 objects with is_in_GALAH == 1
    for B, V, R, I filters, and save as objid_filter.fits if not already present.
    
    Parameters:
        catalog_summary (pd.DataFrame): DataFrame with at least 'GALAH_name' and 'is_in_GALAH' columns
        output_dir (str): Directory to save downloaded files
    """

    os.makedirs(output_dir, exist_ok=True)

    galah_objects = catalog_summary[catalog_summary['is_in_GALAH'] == 1]
    filters = ['B', 'V', 'R', 'I']
    base_url = "https://datacentral.org.au/vo/slink/links"

    for _, row in galah_objects.iterrows():
        obj_id = str(int(row['GALAH_name']))

        for filt in filters:
            filename = f"{obj_id}_{filt}.fits"
            filepath = os.path.join(output_dir, filename)

            # Skip download if file already exists
            if os.path.exists(filepath):
                print(f"Already exists: {filename}, skipping.")
                continue

            params = {
                "ID": obj_id,
                "DR": "galah_dr4",
                "FILT": filt,
                "RESPONSEFORMAT": "fits"
            }
            response = requests.get(base_url, params=params)

            if response.status_code == 200:
                with open(filepath, 'wb') as f:
                    f.write(response.content)
                print(f"Downloaded: {filename}")
            else:
                print(f"Failed to download {filename} — HTTP {response.status_code}")

In [6]:
os.path.getsize("/datax/scratch/emmay/galah_spectra/161116001701343_B.fits")

403200

In [ ]:
download_galah_fits(catalog_summary)

Downloaded: 161212005101036_R.fits
Downloaded: 161212005101036_I.fits
Downloaded: 160109003301143_B.fits
Downloaded: 160109003301143_V.fits
Downloaded: 160109003301143_R.fits
Downloaded: 160109003301143_I.fits
Downloaded: 160331001701167_B.fits
Downloaded: 160331001701167_V.fits
Downloaded: 160331001701167_R.fits
Downloaded: 160331001701167_I.fits
Downloaded: 160110002601245_B.fits
Downloaded: 160110002601245_V.fits
Downloaded: 160110002601245_R.fits
Downloaded: 160110002601245_I.fits
Downloaded: 160331001701165_B.fits
Downloaded: 160331001701165_V.fits
Downloaded: 160331001701165_R.fits
Downloaded: 160331001701165_I.fits
Downloaded: 170102001901245_B.fits
Downloaded: 170102001901245_V.fits
Downloaded: 170102001901245_R.fits
Downloaded: 170102001901245_I.fits
Downloaded: 181225004601301_B.fits
Downloaded: 181225004601301_V.fits
Downloaded: 181225004601301_R.fits
Downloaded: 181225004601301_I.fits
Downloaded: 161228003001143_B.fits
Downloaded: 161228003001143_V.fits
Downloaded: 161228003001143_R.fits
Downloaded: 161228003001143_I.fits
Downloaded: 150408002901233_B.fits
Downloaded: 150408002901233_V.fits
Downloaded: 150408002901233_R.fits
Downloaded: 150408002901233_I.fits
Downloaded: 160110003101141_B.fits
Downloaded: 160110003101141_V.fits
Downloaded: 160110003101141_R.fits
Downloaded: 160110003101141_I.fits
Downloaded: 181225004601057_B.fits